# Generated by Django 4.2.5 on 2023-12-13 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

__all__ = ["Migration"]


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[],
            options={
                "verbose_name": "пользователь",
                "verbose_name_plural": "пользователи",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("auth.user",),
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "visited_countries_count",
                    models.PositiveIntegerField(
                        default=0,
                        verbose_name="стран посещено",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        related_query_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Дополнительное поле",
                "verbose_name_plural": "Дополнительные поля",
            },
        ),
    ]
