# Generated by Django 4.2.5 on 2023-12-18 14:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("countries", "0002_userdesiredcountry_uservisitedcountry"),
        ("users", "0002_profile_desired_countries_profile_visited_countries"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="desired_countries",
            field=models.ManyToManyField(
                blank=True,
                related_name="visited_countries",
                to="countries.userdesiredcountry",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="visited_countries",
            field=models.ManyToManyField(
                blank=True,
                related_name="visited_countries",
                to="countries.uservisitedcountry",
            ),
        ),
    ]
