# Generated by Django 4.2.5 on 2023-12-21 14:50

from django.db import migrations, models

__all__ = ["Migration"]


class Migration(migrations.Migration):
    dependencies = [
        ("countries", "0006_alter_uservisitedcountry_date_visited"),
        ("users", "0004_alter_profile_desired_countries"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="facebook_link",
            field=models.CharField(
                default="",
                max_length=255,
                verbose_name="ссылка на аккаунт Facebook",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="homeland_country",
            field=models.CharField(
                default="",
                max_length=255,
                verbose_name="родная страна",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="instagram_link",
            field=models.CharField(
                default="",
                max_length=255,
                verbose_name="ссылка на аккаунт Instagram",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="twitter_link",
            field=models.CharField(
                default="",
                max_length=255,
                verbose_name="ссылка на аккаунт Twitter",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="desired_countries",
            field=models.ManyToManyField(
                blank=True,
                related_name="desired_countries",
                related_query_name="desired_countries",
                to="countries.userdesiredcountry",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="visited_countries",
            field=models.ManyToManyField(
                blank=True,
                related_name="visited_countries",
                related_query_name="visited_countries",
                to="countries.uservisitedcountry",
            ),
        ),
    ]
