# Generated by Django 4.2.5 on 2023-12-21 15:42

from django.db import migrations, models

__all__ = ["Migration"]


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_alter_profile_homeland_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="users/avatars/",
                verbose_name="аватарка",
            ),
        ),
    ]
