# Generated by Django 4.2.5 on 2023-12-21 20:20

from django.db import migrations, models
import django.db.models.deletion

import users.models

__all__ = ["Migration"]


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_profile_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserUploadedFiles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=users.models.UserUploadedFiles.create_path,
                        verbose_name="файл",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        related_query_name="files",
                        to="users.user",
                    ),
                ),
            ],
        ),
    ]
