# Generated by Django 4.2.5 on 2023-12-23 10:13

from django.db import migrations, models

__all__ = ["Migration"]


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_useruploadedfiles"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="roamway_link",
            field=models.CharField(
                default="",
                max_length=255,
                verbose_name="ссылка на аккаунт RoamWay",
            ),
        ),
    ]
