stages:
  - linting
  - test

flake8:
  stage: linting
  image: registry.gitlab.com/pipeline-components/flake8:latest
  script:
    - pip install flake8-quotes flake8-import-order flake8-dunder-all flake8-commas flake8-print pep8-naming
    - pip install flake8-eradicate flake8-absolute-import flake8-return flake8-use-pathlib flake8-comprehensions
    - flake8 --config=.flake8 .

black_check:
  stage: linting
  image: registry.gitlab.com/pipeline-components/black:latest
  script:
    - black --check --line-length=79 --verbose --diff --color .

django_tests:
  stage: test
  image: python:3.10
  script:
    - pip install -r requirements/test.txt
    - cd RoamWay
    - python3 manage.py test