repos:
      - repo: https://github.com/ambv/black
        rev: 23.9.1
        hooks:
          - id: black
            language_version: python3.12
            args: [--line-length=79]
      -   repo: https://github.com/PyCQA/flake8.git
          rev: 6.1.0
          hooks:
          - id: flake8
            args: [--max-line-length=79, --import-order-style=google]
            additional_dependencies:
              - flake8-import-order
              - flake8-quotes
              - flake8-dunder-all
              - flake8-commas
              - flake8-print
              - flake8-eradicate
              - flake8-absolute-import
              - flake8-return
              - flake8-use-pathlib
              - flake8-comprehensions
      - repo: https://github.com/python-formate/flake8-dunder-all
        rev: v0.3.0
        hooks:
          - id: ensure-dunder-all
      - repo: https://github.com/asottile/add-trailing-comma
        rev: v3.1.0
        hooks:
          - id: add-trailing-comma
