# Generated by Django 4.2.5 on 2023-12-17 17:00

from django.db import migrations, models

__all__ = ["Migration"]


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=128,
                        verbose_name="название страны",
                    ),
                ),
                (
                    "iso",
                    models.CharField(
                        max_length=2,
                        verbose_name="iso-код страны",
                    ),
                ),
            ],
        ),
    ]
