# Generated by Django 4.2.5 on 2023-12-20 19:02

from django.db import migrations, models

__all__ = ["Migration"]


class Migration(migrations.Migration):
    dependencies = [
        ("countries", "0002_userdesiredcountry_uservisitedcountry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uservisitedcountry",
            name="date_visited",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
