# Generated by Django 4.2.5 on 2023-12-21 14:26

from django.db import migrations

__all__ = ["Migration"]


class Migration(migrations.Migration):
    dependencies = [
        ("countries", "0004_alter_uservisitedcountry_date_visited"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="country",
            options={
                "verbose_name": "страна",
                "verbose_name_plural": "страны",
            },
        ),
        migrations.AlterModelOptions(
            name="userdesiredcountry",
            options={
                "verbose_name": "желаемая для посещения страна",
                "verbose_name_plural": "желаемые для посещения страны",
            },
        ),
        migrations.AlterModelOptions(
            name="uservisitedcountry",
            options={
                "verbose_name": "посещенная страна",
                "verbose_name_plural": "посещенные страны",
            },
        ),
    ]
