# Generated by Django 4.2.5 on 2023-12-21 14:31

from django.db import migrations, models

__all__ = []


class Migration(migrations.Migration):
    dependencies = [
        ("countries", "0005_alter_country_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uservisitedcountry",
            name="date_visited",
            field=models.DateTimeField(
                auto_now_add=True,
                null=True,
                verbose_name="дата посещения",
            ),
        ),
    ]
