# Generated by Django 4.2.5 on 2023-12-22 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("countries", "0006_alter_uservisitedcountry_date_visited"),
    ]

    operations = [
        migrations.CreateModel(
            name="CountryTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="текст задачи")),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="countries.country",
                    ),
                ),
            ],
            options={
                "verbose_name": "задача для страны",
                "verbose_name_plural": "задачи для стран",
            },
        ),
    ]
